load myhis

In [15]:
import pandas as pd
mystk_his= pd.read_csv('myhistory_acc.csv',index_col=0)
mystk = mystk_his[mystk_his['stkid']=='00878X']
mystk

         date   Qty   stkid  stkdiv  Interest
index
10.0   113/02  44.0  00878X       0         0
11.0   113/03  44.0  00878X       0         0
12.0   113/04  45.0  00878X       0         0
13.0   113/05  46.1  00878X       0         0
14.0   113/06  46.1  00878X       0         0

get from twse div data

In [82]:
import numpy as np
def get_twse_div_data():
    datestr = datetime.datetime.now().strftime('%Y%m%d')
    print("https://www.twse.com.tw/exchangeReport/TWT49U?response=csv&strDate=20230101&endDate="+datestr)
    res = requests.get("https://www.twse.com.tw/exchangeReport/TWT49U?response=csv&strDate=20200101&endDate="+datestr)
    df = pd.read_csv(io.StringIO(res.text.replace("=", "")), header=1)
    df = df.dropna(thresh=5).dropna(how='all', axis=1)
    df = df[~df['資料日期'].isnull()]
    years = df['資料日期'].str.split('年').str[0].astype(int) #+ 1911

        #years.loc[df['資料日期'].str[3] != '年'] = np.nan
    years.loc[df['資料日期'].str.find('年') == -1] = np.nan
    years.loc[years > datetime.datetime.now().year] = np.nan
    years.ffill(inplace=True)
    dates = years.astype(int).astype(str) +'/'+ df['資料日期'].str.split('年').str[1].str.replace('月', '/').str.replace('日', '')
    df['date'] = dates #pd.to_datetime(dates, errors='coerce')

    float_name_list = ['除權息前收盤價', '除權息參考價', '權值+息值', '漲停價格',
                        '跌停價格', '開盤競價基準', '減除股利參考價' , '最近一次申報每股 (單位)淨值',
                        '最近一次申報每股 (單位)盈餘']

    df[float_name_list] = df[float_name_list].astype(str).apply(lambda s:s.str.replace(',', '')).astype(float)
    df['twse_divide_ratio'] = df['除權息前收盤價'] / df['開盤競價基準']
    df.to_csv('twse_div_data.csv',index=0)
    return df
twse_div_data = get_twse_div_data()

https://www.twse.com.tw/exchangeReport/TWT49U?response=csv&strDate=20230101&endDate=20240606

In [ ]:
twse_div_data = pd.read_csv('twse_div_data.csv')
twse_div_data
stkinfo = twse_div_data[twse_div_data['股票代號'] == '00878']
stkinfo

In [11]:
from datetime import datetime
import pandas as pd

mystk_his= pd.read_csv('myhistory_test.csv',index_col=0)
mystk_his = mystk_his.reset_index(drop=True)
def update_interest_data_twse(stkid):
    global mystk_his
    myhis_stkid = stkid
    stkid = stkid.replace('X','')
    stkinfo = twse_div_data[twse_div_data['股票代號']==stkid]
    #print(stkinfo)
    mystk_his1 =  mystk_his[mystk_his['stkid']==myhis_stkid]
    for idx in stkinfo.index:
        #print(idx)
        s = stkinfo['date'][idx]
        sdiv = stkinfo['權值+息值'][idx]
        print(sdiv)
        year_month = s.split('/')[0] + '/' + s.split('/')[1]
        print(year_month)
        index = mystk_his1.index[(mystk_his1["date"] == year_month)]
        myminimusDate = mystk_his1["date"].min()
        index = mystk_his1.index[(mystk_his1["date"] == year_month)]
        Myyear = str(int(myminimusDate.split('/')[0])+1911)
        stkyear = str(int(year_month.split('/')[0])+1911)
        stkyear = stkyear + '/' + year_month.split('/')[1]
        Myyear = Myyear + '/' + myminimusDate.split('/')[1]
        # 將字串轉換成日期格式
        date_format = '%Y/%m'
        stkdate1 = datetime.strptime(stkyear, date_format)
        mydate2 = datetime.strptime(Myyear, date_format)
        # 比較兩個日期
        if stkdate1 < mydate2:
            continue
        # mystk日期不存在 就新增一筆
        if len(index) == 0: 
            cumulative_sum = mystk_his1['Qty'].sum()
            new_data = [{'date': year_month, 'Qty': 0, 'stkid': stkid, 'stkdiv': sdiv, 'Interest': 0}]
            new_data[0]['Interest'] =  sdiv *  cumulative_sum *1000
            new_data[0]['stkdiv'] = sdiv
            new_df = pd.DataFrame(new_data)
            mystk_his = pd.concat([mystk_his, new_df], ignore_index=True)
            #mystk = pd.merge(mystk_his,mystk_his1)
            continue

        cumulative_sum = mystk_his1.loc[:index[0], 'Qty'].sum()        
        print(index[0])
        #print(mystk_his1.iloc[index[0]].to_frame().T)
        mystk_his.loc[index[0],'stkdiv'] = sdiv
        mystk_his.loc[index[0],'Interest'] = sdiv *  cumulative_sum * 1000
    mystk_his.to_csv('aaa.csv')
    return mystk_his
update_interest_data_twse('2105')

1.0
109/07
1.2
110/08
1.2
111/07
1.4
112/06
2.0
113/06

       date      Qty   stkid  stkdiv  Interest
0    113/03  150.000  00937B     0.0       0.0
1    113/02   50.000  00751B     0.0       0.0
2    113/03   50.000  00751B     0.0       0.0
3    113/04   53.000  00751B     0.0       0.0
4    113/05   54.519  00751B     0.0       0.0
..      ...      ...     ...     ...       ...
102  113/09    9.900    5871     0.0       0.0
103  113/10    9.900    5871     0.0       0.0
104  113/11    9.900    5871     0.0       0.0
105  113/12    9.900    5871     0.0       0.0
106  113/06    0.000    2105     2.0   94400.0

[107 rows x 5 columns]

start from my stkinfo get from otc data

In [26]:
import requests
import pandas as pd
import datetime
import json

datestr = '113/06/04'
def get_otc_div_data():
    y = datetime.datetime.now().year
    m = datetime.datetime.now().month
    d = datetime.datetime.now().day

    y = str(y-1911)
    m = str(m) if m > 9 else '0' + str(m)
    d = str(d) if d > 9 else '0' + str(d)

    datestr = '%s/%s/%s' % (y,m,d)
    res_otc = requests.get('https://www.tpex.org.tw/web/stock/exright/dailyquo/exDailyQ_result.php?l=zh-tw&d=113/01/02&ed=' + datestr)

    df = pd.DataFrame(json.loads(res_otc.text)['aaData'])
    df.columns = ['除權息日期', '代號', '名稱', '除權息前收盤價', '除權息參考價',
                        '權值', '息值',"權+息值","權/息","漲停價格","跌停價格","開盤競價基準",
                        "減除股利參考價","現金股利", "每千股無償配股", "現金增資股數", "現金增資認購價",
                        "公開承銷股數", "員工認購股數","原股東認購數", "按持股比例千股認購"]


    float_name_list = [ '除權息前收盤價', '除權息參考價',
                            '權值', '息值',"權+息值","漲停價格","跌停價格","開盤競價基準",
                            "減除股利參考價","現金股利", "每千股無償配股", "現金增資股數", "現金增資認購價",
                            "公開承銷股數", "員工認購股數","原股東認購數", "按持股比例千股認購"
    ]
    df[float_name_list] = df[float_name_list].astype(str).apply(lambda s:s.str.replace(',', '')).astype(float)

    # set stock id
    df['stock_id'] = df['代號'] + ' ' + df['名稱']

    # set dates
    dates = df['除權息日期'].str.split('/')
    dates = (dates.str[0].astype(int) + 1911).astype(str) + '/' + dates.str[1] + '/' + dates.str[2]
    df['date'] = pd.to_datetime(dates)

    df['otc_divide_ratio'] = df['除權息前收盤價'] / df['開盤競價基準']
    df.to_csv('otc_div_data.csv')
    return df
#return df.set_index(['stock_id', 'date'])
get_otc_div_data()

KeyError: 'aaData'

In [ ]:
y = datetime.datetime.now().year
m = datetime.datetime.now().month
d = datetime.datetime.now().day

y = str(y-1911)
m = str(m) if m > 9 else '0' + str(m)
d = str(d) if d > 9 else '0' + str(d)

datestr = '%s/%s/%s' % (y,m,d)
res_otc = requests.get('https://www.tpex.org.tw/web/stock/exright/dailyquo/exDailyQ_result.php?l=zh-tw&d=113/01/02&ed=' + datestr)


df = pd.DataFrame(json.loads(res_otc.text)['tables'][0]['data'])

df.columns = ['除權息日期', '代號', '名稱', '除權息前收盤價', '除權息參考價',
                    '權值', '息值',"權+息值","權/息","漲停價格","跌停價格","開盤競價基準",
                    "減除股利參考價","現金股利", "每千股無償配股", "現金增資股數", "現金增資認購價",
                    "公開承銷股數", "員工認購股數","原股東認購數", "按持股比例千股認購"]


float_name_list = [ '除權息前收盤價', '除權息參考價',
                        '權值', '息值',"權+息值","漲停價格","跌停價格","開盤競價基準",
                        "減除股利參考價","現金股利", "每千股無償配股", "現金增資股數", "現金增資認購價",
                        "公開承銷股數", "員工認購股數","原股東認購數", "按持股比例千股認購"
]
df[float_name_list] = df[float_name_list].astype(str).apply(lambda s:s.str.replace(',', '')).astype(float)

# set stock id
df['stock_id'] = df['代號'] + ' ' + df['名稱']

# set dates
dates = df['除權息日期'].str.split('/')
dates = (dates.str[0].astype(int) + 1911).astype(str) + '/' + dates.str[1] + '/' + dates.str[2]
df['date'] = pd.to_datetime(dates)

df['otc_divide_ratio'] = df['除權息前收盤價'] / df['開盤競價基準']
df.to_csv('otc_div_data.csv')
return df

KeyError: 'aaData'

In [23]:
ss = json.loads(res_otc.text)
df = pd.DataFrame(json.loads(res_otc.text)['tables'][0]['data'])

df.columns = ['除權息日期', '代號', '名稱', '除權息前收盤價', '除權息參考價',
                    '權值', '息值',"權+息值","權/息","漲停價格","跌停價格","開盤競價基準",
                    "減除股利參考價","現金股利", "每千股無償配股", "現金增資股數", "現金增資認購價",
                    "公開承銷股數", "員工認購股數","原股東認購數", "按持股比例千股認購"]

df

,除權息日期,代號,名稱,除權息前收盤價,除權息參考價,權值,息值,權+息值,權/息,漲停價格,...,開盤競價基準,減除股利參考價,現金股利,每千股無償配股,現金增資股數,現金增資認購價,公開承銷股數,員工認購股數,原股東認購數,按持股比例千股認購
0,113/01/03,6629,泰金-KY,55.00,53.50,0.000000,1.500000,1.500000,除息,58.80,...,53.50,53.50,1.50000000,0.00000000,0,0.00,0,0,0,0.00000000
1,113/01/08,6613,朋億*,140.50,137.07,0.000000,3.429363,3.429363,除息,150.50,...,137.00,137.07,3.42936322,0.00000000,0,0.00,0,0,0,0.00000000
2,113/01/10,1799,易威,39.25,38.72,0.528412,0.000000,0.528412,除權,43.15,...,39.25,39.25,0.00000000,0.00000000,6000000,28.60,600000,600000,4800000,41.76517920
3,113/01/11,6763,綠界科技,459.50,450.40,0.000000,9.100000,9.100000,除息,495.00,...,450.50,450.40,9.10000003,0.00000000,0,0.00,0,0,0,0.00000000
4,113/01/15,5536,聖暉*,179.00,174.50,0.000000,4.500000,4.500000,除息,191.50,...,174.50,174.50,4.50000000,0.00000000,0,0.00,0,0,0,0.00000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,113/10/29,2061,風青,20.95,20.54,0.409564,0.000000,0.409564,除權,23.00,...,20.95,20.95,0.00000000,0.00000000,10000000,18.60,1000000,1500000,7500000,158.30114754
965,113/10/30,6596,寬宏藝術,73.80,73.30,0.500000,0.000000,0.500000,除權,81.10,...,73.80,73.80,0.00000000,0.00000000,5000000,70.00,500000,750000,3750000,113.63636364
966,113/10/31,00950B,凱基A級公司債,15.06,14.98,0.000000,0.082000,0.082000,除息,9999.95,...,14.98,14.98,0.08200000,0.00000000,0,0.00,0,0,0,0.00000000
967,113/10/31,00959B,大華投等美債15Y+,9.90,9.85,0.000000,0.055000,0.055000,除息,9999.95,...,9.85,9.85,0.05500000,0.00000000,0,0.00,0,0,0,0.00000000
968,113/10/31,6690,安碁資訊,230.50,222.40,8.102215,0.000000,8.102215,除權,253.50,...,230.50,230.50,0.00000000,0.00000000,8000000,200.00,800000,800000,6400000,289.39345844

In [25]:
ss = json.loads(res_otc.text)
df = pd.DataFrame(json.loads(res_otc.text)['tables'][0]['data'])

df.columns = ['除權息日期', '代號', '名稱', '除權息前收盤價', '除權息參考價',
                    '權值', '息值',"權+息值","權/息","漲停價格","跌停價格","開盤競價基準",
                    "減除股利參考價","現金股利", "每千股無償配股", "現金增資股數", "現金增資認購價",
                    "公開承銷股數", "員工認購股數","原股東認購數", "按持股比例千股認購"]

df

,除權息日期,代號,名稱,除權息前收盤價,除權息參考價,權值,息值,權+息值,權/息,漲停價格,...,開盤競價基準,減除股利參考價,現金股利,每千股無償配股,現金增資股數,現金增資認購價,公開承銷股數,員工認購股數,原股東認購數,按持股比例千股認購
0,113/01/03,6629,泰金-KY,55.00,53.50,0.000000,1.500000,1.500000,除息,58.80,...,53.50,53.50,1.50000000,0.00000000,0,0.00,0,0,0,0.00000000
1,113/01/08,6613,朋億*,140.50,137.07,0.000000,3.429363,3.429363,除息,150.50,...,137.00,137.07,3.42936322,0.00000000,0,0.00,0,0,0,0.00000000
2,113/01/10,1799,易威,39.25,38.72,0.528412,0.000000,0.528412,除權,43.15,...,39.25,39.25,0.00000000,0.00000000,6000000,28.60,600000,600000,4800000,41.76517920
3,113/01/11,6763,綠界科技,459.50,450.40,0.000000,9.100000,9.100000,除息,495.00,...,450.50,450.40,9.10000003,0.00000000,0,0.00,0,0,0,0.00000000
4,113/01/15,5536,聖暉*,179.00,174.50,0.000000,4.500000,4.500000,除息,191.50,...,174.50,174.50,4.50000000,0.00000000,0,0.00,0,0,0,0.00000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,113/10/29,2061,風青,20.95,20.54,0.409564,0.000000,0.409564,除權,23.00,...,20.95,20.95,0.00000000,0.00000000,10000000,18.60,1000000,1500000,7500000,158.30114754
965,113/10/30,6596,寬宏藝術,73.80,73.30,0.500000,0.000000,0.500000,除權,81.10,...,73.80,73.80,0.00000000,0.00000000,5000000,70.00,500000,750000,3750000,113.63636364
966,113/10/31,00950B,凱基A級公司債,15.06,14.98,0.000000,0.082000,0.082000,除息,9999.95,...,14.98,14.98,0.08200000,0.00000000,0,0.00,0,0,0,0.00000000
967,113/10/31,00959B,大華投等美債15Y+,9.90,9.85,0.000000,0.055000,0.055000,除息,9999.95,...,9.85,9.85,0.05500000,0.00000000,0,0.00,0,0,0,0.00000000
968,113/10/31,6690,安碁資訊,230.50,222.40,8.102215,0.000000,8.102215,除權,253.50,...,230.50,230.50,0.00000000,0.00000000,8000000,200.00,800000,800000,6400000,289.39345844

In [ ]:
data = json_data['tables'][0]['data']

{'date': '20240102~20241104',
 'tables': [{'title': '',
   'totalCount': 969,
   'fields': ['除權息日期',
    '代號',
    '名稱',
    '除權息前收盤價',
    '除權息參考價',
    '權值',
    '息值',
    '權值+息值',
    '權/息',
    '漲停價',
    '跌停價',
    '開始交易基準價',
    '減除股利參考價',
    '現金股利',
    '每仟股無償配股',
    '現金增資股數',
    '現金增資認購價',
    '公開承銷股數',
    '員工認購股數',
    '原股東認購股數',
    '按持股比例仟股認購'],
   'data': [['113/01/03',
     '6629',
     '泰金-KY           ',
     '55.00',
     '53.50',
     '0.000000',
     '1.500000',
     '1.500000',
     '除息',
     '58.80',
     '48.15',
     '53.50',
     '53.50',
     '1.50000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/08',
     '6613',
     '朋億*             ',
     '140.50',
     '137.07',
     '0.000000',
     '3.429363',
     '3.429363',
     '除息',
     '150.50',
     '123.50',
     '137.00',
     '137.07',
     '3.42936322',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/10',
     '1799',
     '易威              ',
     '39.25',
     '38.72',
     '0.528412',
     '0.000000',
     '0.528412',
     '除權',
     '43.15',
     '34.85',
     '39.25',
     '39.25',
     '0.00000000',
     '0.00000000',
     '6000000',
     '28.60',
     '600000',
     '600000',
     '4800000',
     '41.76517920'],
    ['113/01/11',
     '6763',
     '綠界科技            ',
     '459.50',
     '450.40',
     '0.000000',
     '9.100000',
     '9.100000',
     '除息',
     '495.00',
     '405.50',
     '450.50',
     '450.40',
     '9.10000003',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/15',
     '5536',
     '聖暉*             ',
     '179.00',
     '174.50',
     '0.000000',
     '4.500000',
     '4.500000',
     '除息',
     '191.50',
     '157.50',
     '174.50',
     '174.50',
     '4.50000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/16',
     '00734B',
     '台新JPM新興債        ',
     '15.77',
     '15.55',
     '0.000000',
     '0.220000',
     '0.220000',
     '除息',
     '9999.95',
     '0.01',
     '15.55',
     '15.55',
     '0.22000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/16',
     '00842B',
     '台新美元銀行債         ',
     '33.56',
     '33.11',
     '0.000000',
     '0.450000',
     '0.450000',
     '除息',
     '9999.95',
     '0.01',
     '33.11',
     '33.11',
     '0.45000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/16',
     '8087',
     '華鎂鑫             ',
     '52.00',
     '49.21',
     '2.791494',
     '0.000000',
     '2.791494',
     '除權',
     '57.20',
     '44.30',
     '52.00',
     '52.00',
     '0.00000000',
     '0.00000000',
     '9000000',
     '40.00',
     '900000',
     '1350000',
     '6750000',
     '227.35720157'],
    ['113/01/17',
     '00694B',
     '富邦美債1-3         ',
     '40.38',
     '40.30',
     '0.000000',
     '0.078000',
     '0.078000',
     '除息',
     '9999.95',
     '0.01',
     '40.30',
     '40.30',
     '0.07800000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00695B',
     '富邦美債7-10        ',
     '35.30',
     '35.13',
     '0.000000',
     '0.174000',
     '0.174000',
     '除息',
     '9999.95',
     '0.01',
     '35.13',
     '35.13',
     '0.17400000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00696B',
     '富邦美債20年         ',
     '32.11',
     '31.90',
     '0.000000',
     '0.214000',
     '0.214000',
     '除息',
     '9999.95',
     '0.01',
     '31.90',
     '31.90',
     '0.21400000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00719B',
     '元大美債1-3         ',
     '31.31',
     '30.97',
     '0.000000',
     '0.340000',
     '0.340000',
     '除息',
     '9999.95',
     '0.01',
     '30.97',
     '30.97',
     '0.34000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00720B',
     '元大投資級公司債        ',
     '36.22',
     '35.74',
     '0.000000',
     '0.480000',
     '0.480000',
     '除息',
     '9999.95',
     '0.01',
     '35.74',
     '35.74',
     '0.48000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00722B',
     '群益投資級電信債        ',
     '39.24',
     '38.83',
     '0.000000',
     '0.409000',
     '0.409000',
     '除息',
     '9999.95',
     '0.01',
     '38.83',
     '38.83',
     '0.40900000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00723B',
     '群益投資級科技債        ',
     '34.99',
     '34.59',
     '0.000000',
     '0.396000',
     '0.396000',
     '除息',
     '9999.95',
     '0.01',
     '34.59',
     '34.59',
     '0.39600000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00724B',
     '群益投資級金融債        ',
     '34.90',
     '34.49',
     '0.000000',
     '0.409000',
     '0.409000',
     '除息',
     '9999.95',
     '0.01',
     '34.49',
     '34.49',
     '0.40900000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00725B',
     '國泰投資級公司債        ',
     '38.57',
     '37.90',
     '0.000000',
     '0.670000',
     '0.670000',
     '除息',
     '9999.95',
     '0.01',
     '37.90',
     '37.90',
     '0.67000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00726B',
     '國泰5Y+新興債        ',
     '34.25',
     '33.67',
     '0.000000',
     '0.580000',
     '0.580000',
     '除息',
     '9999.95',
     '0.01',
     '33.67',
     '33.67',
     '0.58000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00727B',
     '國泰1-5Y非投等債      ',
     '39.25',
     '38.72',
     '0.000000',
     '0.530000',
     '0.530000',
     '除息',
     '9999.95',
     '0.01',
     '38.72',
     '38.72',
     '0.53000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00740B',
     '富邦全球投等債         ',
     '41.26',
     '40.76',
     '0.000000',
     '0.505000',
     '0.505000',
     '除息',
     '9999.95',
     '0.01',
     '40.76',
     '40.76',
     '0.50500000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00741B',
     '富邦全球非投等債        ',
     '37.93',
     '37.45',
     '0.000000',
     '0.483000',
     '0.483000',
     '除息',
     '9999.95',
     '0.01',
     '37.45',
     '37.45',
     '0.48300000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00746B',
     '富邦A級公司債         ',
     '37.64',
     '37.26',
     '0.000000',
     '0.379000',
     '0.379000',
     '除息',
     '9999.95',
     '0.01',
     '37.26',
     '37.26',
     '0.37900000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00749B',
     '凱基新興債10+        ',
     '32.25',
     '31.83',
     '0.000000',
     '0.425000',
     '0.425000',
     '除息',
     '9999.95',
     '0.01',
     '31.83',
     '31.83',
     '0.42500000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00750B',
     '凱基科技債10+        ',
     '36.38',
     '35.98',
     '0.000000',
     '0.400000',
     '0.400000',
     '除息',
     '9999.95',
     '0.01',
     '35.98',
     '35.98',
     '0.40000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00772B',
     '中信高評級公司債        ',
     '36.50',
     '36.37',
     '0.000000',
     '0.130000',
     '0.130000',
     '除息',
     '9999.95',
     '0.01',
     '36.37',
     '36.37',
     '0.13000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00773B',
     '中信優先金融債         ',
     '37.23',
     '37.09',
     '0.000000',
     '0.140000',
     '0.140000',
     '除息',
     '9999.95',
     '0.01',
     '37.09',
     '37.09',
     '0.14000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00782B',
     '國泰A級公用債         ',
     '33.31',
     '32.86',
     '0.000000',
     '0.450000',
     '0.450000',
     '除息',
     '9999.95',
     '0.01',
     '32.86',
     '32.86',
     '0.45000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00784B',
     '富邦中國投等債         ',
     '37.45',
     '37.25',
     '0.000000',
     '0.200000',
     '0.200000',
     '除息',
     '9999.95',
     '0.01',
     '37.25',
     '37.25',
     '0.20000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00785B',
     '富邦金融投等債         ',
     '36.22',
     '35.84',
     '0.000000',
     '0.385000',
     '0.385000',
     '除息',
     '9999.95',
     '0.01',
     '35.84',
     '35.84',
     '0.38500000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00788B',
     '元大10年IG電能債      ',
     '32.41',
     '31.98',
     '0.000000',
     '0.430000',
     '0.430000',
     '除息',
     '9999.95',
     '0.01',
     '31.98',
     '31.98',
     '0.43000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00848B',
     '中信新興亞洲債         ',
     '35.02',
     '34.62',
     '0.000000',
     '0.400000',
     '0.400000',
     '除息',
     '9999.95',
     '0.01',
     '34.62',
     '34.62',
     '0.40000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00849B',
     '中信EM主權債0-5      ',
     '36.41',
     '36.24',
     '0.000000',
     '0.169000',
     '0.169000',
     '除息',
     '9999.95',
     '0.01',
     '36.24',
     '36.24',
     '0.16900000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00858',
     '永豐美國500大        ',
     '29.21',
     '27.71',
     '0.000000',
     '1.500000',
     '1.500000',
     '除息',
     '9999.95',
     '0.01',
     '27.71',
     '27.71',
     '1.50000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00870B',
     '元大15年EM主權債      ',
     '30.22',
     '29.86',
     '0.000000',
     '0.360000',
     '0.360000',
     '除息',
     '9999.95',
     '0.01',
     '29.86',
     '29.86',
     '0.36000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00884B',
     '中信低碳新興債         ',
     '30.83',
     '30.47',
     '0.000000',
     '0.359000',
     '0.359000',
     '除息',
     '9999.95',
     '0.01',
     '30.47',
     '30.47',
     '0.35900000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00888',
     '永豐台灣ESG         ',
     '14.12',
     '13.91',
     '0.000000',
     '0.208000',
     '0.208000',
     '除息',
     '15.30',
     '12.52',
     '13.91',
     '13.91',
     '0.20800000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '00928',
     '中信上櫃ESG 30      ',
     '16.37',
     '15.77',
     '0.000000',
     '0.600000',
     '0.600000',
     '除息',
     '17.34',
     '14.20',
     '15.77',
     '15.77',
     '0.60000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/17',
     '6761',
     '穩得              ',
     '74.60',
     '70.93',
     '3.670494',
     '0.000000',
     '3.670494',
     '除權',
     '82.00',
     '63.90',
     '74.60',
     '74.60',
     '0.00000000',
     '0.00000000',
     '5000000',
     '52.50',
     '500000',
     '750000',
     '3750000',
     '149.37298003'],
    ['113/01/18',
     '00789B',
     '復華公司債A3         ',
     '53.55',
     '52.95',
     '0.000000',
     '0.605000',
     '0.605000',
     '除息',
     '9999.95',
     '0.01',
     '52.95',
     '52.95',
     '0.60500000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/18',
     '00790B',
     '復華次順位金融債        ',
     '54.65',
     '54.05',
     '0.000000',
     '0.600000',
     '0.600000',
     '除息',
     '9999.95',
     '0.01',
     '54.05',
     '54.05',
     '0.60000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/18',
     '00791B',
     '復華信用債1-5        ',
     '55.15',
     '54.60',
     '0.000000',
     '0.550000',
     '0.550000',
     '除息',
     '9999.95',
     '0.01',
     '54.60',
     '54.60',
     '0.55000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/19',
     '00931B',
     '統一美債20年         ',
     '14.85',
     '14.74',
     '0.000000',
     '0.110000',
     '0.110000',
     '除息',
     '9999.95',
     '0.01',
     '14.74',
     '14.74',
     '0.11000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/19',
     '6488',
     '環球晶             ',
     '580.00',
     '572.00',
     '0.000000',
     '8.000000',
     '8.000000',
     '除息',
     '629.00',
     '515.00',
     '572.00',
     '572.00',
     '8.00000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/22',
     '00834B',
     '第一金金融債10+       ',
     '34.97',
     '34.53',
     '0.000000',
     '0.440000',
     '0.440000',
     '除息',
     '9999.95',
     '0.01',
     '34.53',
     '34.53',
     '0.44000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/25',
     '3289',
     '宜特              ',
     '98.00',
     '96.98',
     '0.000000',
     '1.020118',
     '1.020118',
     '除息',
     '106.50',
     '87.30',
     '97.00',
     '96.98',
     '1.02011784',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/25',
     '5483',
     '中美晶             ',
     '203.50',
     '200.00',
     '0.000000',
     '3.500000',
     '3.500000',
     '除息',
     '220.00',
     '180.00',
     '200.00',
     '200.00',
     '3.50000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/01/29',
     '6624',
     '萬年清             ',
     '44.60',
     '43.28',
     '1.324138',
     '0.000000',
     '1.324138',
     '除權',
     '49.05',
     '39.00',
     '44.60',
     '44.60',
     '0.00000000',
     '0.00000000',
     '2880000',
     '35.00',
     '288000',
     '288000',
     '2304000',
     '128.00000000'],
    ['113/01/29',
     '8423',
     '保綠-KY           ',
     '23.00',
     '20.73',
     '2.268571',
     '0.000000',
     '2.268571',
     '除權',
     '25.30',
     '18.70',
     '23.00',
     '23.00',
     '0.00000000',
     '0.00000000',
     '12500000',
     '16.00',
     '1250000',
     '1250000',
     '10000000',
     '383.57484932'],
    ['113/02/22',
     '5604',
     '中連              ',
     '50.00',
     '48.00',
     '0.000000',
     '2.000000',
     '2.000000',
     '除息',
     '52.80',
     '43.20',
     '48.00',
     '48.00',
     '2.00000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00679B',
     '元大美債20年         ',
     '29.95',
     '29.64',
     '0.000000',
     '0.310000',
     '0.310000',
     '除息',
     '9999.95',
     '0.01',
     '29.64',
     '29.64',
     '0.31000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00718B',
     '富邦中國政策債         ',
     '20.30',
     '19.99',
     '0.000000',
     '0.308000',
     '0.308000',
     '除息',
     '9999.95',
     '0.01',
     '19.99',
     '19.99',
     '0.30800000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00721B',
     '元大中國債3-5        ',
     '45.89',
     '45.35',
     '0.000000',
     '0.540000',
     '0.540000',
     '除息',
     '9999.95',
     '0.01',
     '45.35',
     '45.35',
     '0.54000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00754B',
     '群益AAA-AA公司債     ',
     '36.72',
     '36.30',
     '0.000000',
     '0.418000',
     '0.418000',
     '除息',
     '9999.95',
     '0.01',
     '36.30',
     '36.30',
     '0.41800000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00755B',
     '群益投資級公用債        ',
     '34.56',
     '34.13',
     '0.000000',
     '0.434000',
     '0.434000',
     '除息',
     '9999.95',
     '0.01',
     '34.13',
     '34.13',
     '0.43400000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00756B',
     '群益投等新興公債        ',
     '32.99',
     '32.51',
     '0.000000',
     '0.479000',
     '0.479000',
     '除息',
     '9999.95',
     '0.01',
     '32.51',
     '32.51',
     '0.47900000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00761B',
     '國泰A級公司債         ',
     '37.18',
     '36.70',
     '0.000000',
     '0.480000',
     '0.480000',
     '除息',
     '9999.95',
     '0.01',
     '36.70',
     '36.70',
     '0.48000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00772B',
     '中信高評級公司債        ',
     '35.60',
     '35.47',
     '0.000000',
     '0.130000',
     '0.130000',
     '除息',
     '9999.95',
     '0.01',
     '35.47',
     '35.47',
     '0.13000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00773B',
     '中信優先金融債         ',
     '36.80',
     '36.66',
     '0.000000',
     '0.140000',
     '0.140000',
     '除息',
     '9999.95',
     '0.01',
     '36.66',
     '36.66',
     '0.14000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00780B',
     '國泰A級金融債         ',
     '36.81',
     '36.53',
     '0.000000',
     '0.280000',
     '0.280000',
     '除息',
     '9999.95',
     '0.01',
     '36.53',
     '36.53',
     '0.28000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00786B',
     '元大10年IG銀行債      ',
     '34.34',
     '33.82',
     '0.000000',
     '0.520000',
     '0.520000',
     '除息',
     '9999.95',
     '0.01',
     '33.82',
     '33.82',
     '0.52000000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00794B',
     '群益7+中國政金債       ',
     '40.20',
     '39.80',
     '0.000000',
     '0.402000',
     '0.402000',
     '除息',
     '9999.95',
     '0.01',
     '39.80',
     '39.80',
     '0.40200000',
     '0.00000000',
     '0',
     '0.00',
     '0',
     '0',
     '0',
     '0.00000000'],
    ['113/02/27',
     '00795B',
     '中信美國公債20年       ',
     '30.31',
     '29.96',
     '0.000000',
     '0.350000',
     '0.350000',
     '除息',
     '9999.95',
     '0.01',
     '29.96',
     '29.96',
     '0.35000000',

In [11]:
df.columns = ['除權息日期', '代號', '名稱', '除權息前收盤價', '除權息參考價',
                    '權值', '息值',"權+息值","權/息","漲停價格","跌停價格","開盤競價基準",
                    "減除股利參考價","現金股利", "每千股無償配股", "現金增資股數", "現金增資認購價",
                    "公開承銷股數", "員工認購股數","原股東認購數", "按持股比例千股認購"]

ValueError: Length mismatch: Expected axis has 6 elements, new values have 21 elements

In [16]:
import pandas as pd
otc_div_data = pd.read_csv('otc_div_data.csv')

In [7]:

data = [{'date': '113/02', 'Qty': 0, 'stkid': '00937B','stkdiv':0,'Interest':0},
        {'date': '113/03', 'Qty': 165, 'stkid': '00937B','stkdiv':0,'Interest':0},
        {'date': '113/04', 'Qty': 170, 'stkid': '00937B','stkdiv':0,'Interest':0},
        {'date': '113/05', 'Qty': 170, 'stkid': '00937B','stkdiv':0,'Interest':0},
        {'date': '113/06', 'Qty': 232, 'stkid': '00937B','stkdiv':0,'Interest':0},
        {'date': '113/07', 'Qty': 232, 'stkid': '00937B','stkdiv':0,'Interest':0},
        {'date': '113/08', 'Qty': 232, 'stkid': '00937B','stkdiv':0,'Interest':0}]

mystk_his = pd.DataFrame(data)
print(mystk_his)
mystk_his.to_csv('myhistory.csv')

     date  Qty   stkid  stkdiv  Interest
0  113/02    0  00937B       0         0
1  113/03  165  00937B       0         0
2  113/04  170  00937B       0         0
3  113/05  170  00937B       0         0
4  113/06  232  00937B       0         0
5  113/07  232  00937B       0         0
6  113/08  232  00937B       0         0

In [51]:
from datetime import datetime
def update_interest_data(stkid):
    mystk_his= pd.read_csv('myhistory_test.csv',index_col=0)
    mystk_his = mystk_his.reset_index(drop=True)
    myhis_stkid = stkid
    stkid = stkid.replace('X','')
    stkinfo = otc_div_data[otc_div_data['代號']==myhis_stkid]
    if len(stkinfo) == 0: #not found in otc data
        return update_interest_data_twse(myhis_stkid)
    #print(stkinfo)
    mystk_his1 =  mystk_his[mystk_his['stkid']==stkid]
    cumulative_sum = 0
    for idx in stkinfo.index:
        #print(idx)
        s = stkinfo['除權息日期'][idx]
        sdiv = stkinfo['息值'][idx]
        print(sdiv)
        year_month = s.split('/')[0] + '/' + s.split('/')[1]
        print(year_month)
        #做日期處理 比大小 ,以前的日期 不處理
        myminimusDate = mystk_his1["date"].min()
        index = mystk_his1.index[(mystk_his1["date"] == year_month)]
        Myyear = str(int(myminimusDate.split('/')[0])+1911)
        stkyear = str(int(year_month.split('/')[0])+1911)
        stkyear = stkyear + '/' + year_month.split('/')[1]
        Myyear = Myyear + '/' + myminimusDate.split('/')[1]
        # 將字串轉換成日期格式
        date_format = '%Y/%m'
        stkdate1 = datetime.strptime(stkyear, date_format)
        mydate2 = datetime.strptime(Myyear, date_format)

        # 比較兩個日期
        if stkdate1 < mydate2:
            continue
        # mystk日期不存在 就新增一筆
        if len(index) == 0: 
            new_data = [{'date': year_month, 'Qty': 0, 'stkid': stkid, 'stkdiv': sdiv, 'Interest': 0}]
            new_data[0]['Interest'] =  sdiv *  cumulative_sum *1000
            new_data[0]['stkdiv'] = sdiv
            new_df = pd.DataFrame(new_data)
            mystk_his = pd.concat([mystk_his, new_df], ignore_index=True)
            #mystk = pd.merge(mystk_his,mystk_his1)
            continue
            #mystk_his.loc[mystk_his['stkid'] == myhis_stkid, :] = mystk_his1
            #mystk_his1 =  mystk_his[mystk_his['stkid']==myhis_stkid]
            #index = mystk_his1.index[(mystk_his1["date"] == year_month)]
            #continue
        cumulative_sum = mystk_his1.loc[:index[0], 'Qty'].sum()   
        print(index[0])
        #print(mystk_his1.iloc[index[0]].to_frame().T)
        mystk_his.loc[index[0],'stkdiv'] = sdiv
        mystk_his.loc[index[0],'Interest'] = sdiv *  cumulative_sum *1000

    #mystk_his.loc[mystk_his['stkid'] == myhis_stkid, :] = mystk_his1
    #mystk_his['stkdiv'] = mystk_his1['stkdiv']
    #mystk_his['Interest'] = mystk_his1['Interest']
    #mystk_his.to_csv('aaa.csv')
    
    return mystk_his

update_interest_data('00937B')

0.084
113/02
0.084
113/03
2.0
0.084
113/04
0.084
113/05

       date      Qty   stkid  stkdiv  Interest
0    113/03  150.000  00937B   0.084   12600.0
1    113/02   50.000  00751B   0.000       0.0
2    113/03   50.000  00751B   0.000       0.0
3    113/04   53.000  00751B   0.000       0.0
4    113/05   54.519  00751B   0.000       0.0
..      ...      ...     ...     ...       ...
123  113/10    9.900    5871   0.000       0.0
124  113/11    9.900    5871   0.000       0.0
125  113/12    9.900    5871   0.000       0.0
126  113/04    0.000  00937B   0.084   12600.0
127  113/05    0.000  00937B   0.084   12600.0

[128 rows x 5 columns]

In [ ]:
new_data = [{'date': 'year_month', 'Qty': 0, 'stkid': 'stkid', 'stkdiv': 'sdiv', 'Interest': 0}]
new_data[0]['stkdiv'] = 100
new_data

In [ ]:
mystk_his= pd.read_csv('myhistory.csv',index_col=0)
mystk_his = mystk_his.reset_index(drop=True)
ids = mystk_his.value_counts('stkid')
for a in ids.index:
    print(a)
    mystk_his = update_interest_data(a)
mystk_his.to_csv('result.csv')
mystk_his.head(20)

In [ ]:
stkinfo = twse_div_data[twse_div_data['股票代號']=='5871']
stkinfo

In [24]:
import pandas as pd
hisdf = pd.read_csv('myhistory.csv')
del hisdf['Unnamed: 0']
hisdf = hisdf.reset_index(drop=True)

hisdf
hisdf.groupby(['stkid']).agg({'Qty': 'sum','Interest':'sum'})

            Qty      Interest
stkid
0056X    13.630   10507.00000
00687B    5.000    1700.00000
00713X    8.571   19016.50000
00751B   54.519   47623.93000
00857B    4.000     840.00000
00878X   46.815   40822.85000
00882X   30.942       0.00000
00933B   36.000    3362.00000
00937B  235.000   66696.00000
00940X    7.850       0.00000
1584      3.000    4500.00000
2105      9.800   30120.00000
2887     17.777   22530.05427
2892     78.010  127050.28440
5871      9.900  102494.10600

In [33]:

writer = pd.ExcelWriter('output.xlsx', engine='xlsxwriter')

s = hisdf.groupby(['date','stkid']).agg({'Qty': 'sum','Interest':'sum'})
#s.to_csv('sumbydate.csv')
s.to_excel(writer, sheet_name='sumbydate_stkid')

s = hisdf.groupby(['stkid']).agg({'Qty': 'sum','Interest':'sum'})
s.to_excel(writer, sheet_name='sumbystkid')

s = hisdf.groupby(['date']).agg({'Interest':'sum'})
s.to_excel(writer, sheet_name='sumbydate')
writer.close()

In [ ]:
s = hisdf.groupby(['date','stkid']).sum(['Interest','Qty'])
s.to_csv('sumbydate.csv')

s = hisdf.groupby(['stkid']).sum(['Qty'])
hisdf
#s.to_csv('sumbyst.csv')

In [2]:
import requests

def get_stock_price(stock_symbol):
    url = f"https://www.twse.com.tw/exchangeReport/STOCK_DAY_AVG?response=json&date=20210910&stockNo={stock_symbol}"
    response = requests.get(url)
    data = response.json()
    
    if data['stat'] == 'OK':
        price = data['data'][0][1]  # 获取当日收盘价
        volume = data['data'][0][2]  # 获取当日成交量
        print(f"Stock Price for {stock_symbol}: {price}")
        print(f"Volume for {stock_symbol}: {volume}")
    else:
        print("Failed to fetch data from TWSE")

if __name__ == "__main__":
    stock_symbol = "2330"  # 台積電代號
    get_stock_price(stock_symbol)

KeyboardInterrupt: